### ISSUE TITLE
The input box is blocked with Chinese input method

### ISSUE THREAD

**Issue by JellyBo** [ryngonzalez/ChatGPT-for-Mac#3]
When using a Chinese input method, the input method box is blocked and the candidate options cannot be seen.

Device Version : MacBook Pro 14' M1 Pro

<img width="691" alt="image" src="https://user-images.githubusercontent.com/9100842/225183173-6fa09e82-94ff-47e5-b717-db588fd801ff.png">

**Comment by ryngonzalez** [comment]
Thanks for sharing! I'm going to close this in favor of #5, and you can keep track of that issue there.
