### ISSUE TITLE
Possible to choose model for Pro users?

### ISSUE THREAD

**Issue by junxi-liu** [ryngonzalez/ChatGPT-for-Mac#4]

**Comment by ryngonzalez** [comment]
Yes, the current release (1.0.2) and all previous versions should allow this.

<img width="545" alt="Screenshot 2023-03-22 at 11 05 30 AM" src="https://user-images.githubusercontent.com/635300/227038014-2f6578a9-65bd-4d1e-b571-b77945c75013.png">
